### ISSUE TITLE
Render photos

### ISSUE THREAD

**Issue by sarina-nikolic** [sarina-nikolic/capstone-project#1]
## Value proposition

**As a** user,
**I want to** have a list of my photos
**so that** I have a quick overview and don't have to remember all of my clothes.

## Description

![render](https://user-images.githubusercontent.com/104504965/176154789-415c71eb-b201-4b82-8429-db82bde0b21f.png)

## Acceptance criteria

- [x] Items (photos) are rendered

## Complexity

Small 

## Tasks

- [x] Create branch
- [x] Add base styles
- [x] Write specs for rendering

**Comment by ahohnsen** [comment]
Hey Sarina,

nicely done.
My suggestions:

- I would suggest to phrase the value proposition a bit more specific, for example:

_As a user,
I want to have a list with photos of my clothes
so that I have a quick overview and don't have to remember all the clothes in my closet._

- in your scribble you can indicate photos with a crossed out box :) As well, as I understand correctly the add-button will not have any functionality yet, therefore it should not be included in this story (neither in the scribble nor the acceptance criteria and tasks etc.)
-
