### ISSUE TITLE
Upload photos

### ISSUE THREAD

**Issue by sarina-nikolic** [sarina-nikolic/capstone-project#2]
## Value proposition

**As a** user,
**I want to** upload photos of my clothes
**so that** I have a quick overview of my wardrobe and don't have to remember it piece by piece.

## Description

<img src=https://user-images.githubusercontent.com/104504965/175265423-df9fd389-ecaa-42e8-a0e0-a9fd0d79d23e.png width=200px> <img src=https://user-images.githubusercontent.com/104504965/175545439-b235fb2e-63b8-4ae5-abbe-cc9c54220fc3.png width=200px> 
<img src=https://user-images.githubusercontent.com/104504965/175545523-74c01a06-277f-48de-9834-43b77d7479fc.png width=200px> <img src=https://user-images.githubusercontent.com/104504965/175545613-19c45760-0b74-4b52-83c4-017fa2a5b026.png width=200px>

## Acceptance criteria

- [ ] Photos are added to the top
- [ ] The button is always at the bottom
- [ ] Photos scroll beneath button
- [ ] Photo-Gallery is horizontally scrollable

## Complexity

 Large

## Tasks

- [ ] Create branch
- [ ] Implement cloudinary for upload
- [ ] Add base style
- [ ] Setup Storybook for button
- [ ] Write specs for button
