### ISSUE TITLE
Color Category Filter

### ISSUE THREAD

**Issue by sarina-nikolic** [sarina-nikolic/capstone-project#4]
**As a** user,
**I want to** search through my clothes by color,
**so that** I find my favorite color quickly.

## Description

<img src=https://user-images.githubusercontent.com/104504965/177748954-c445d7ab-8f95-48aa-9eae-12a1d7b6d062.png width=320px>

## Acceptance criteria

- [x] Filter are shown at the top
- [x] Filter are not sticky

## Complexity

Medium 

## Tasks

- [x] Create branch
- [x] Filter are drop-downs
- [x] Setup Storybook
- [x] Write spec
