### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by sarina-nikolic** [sarina-nikolic/capstone-project#8]
## Value proposition

**As a** user,
**I want to** not only to search by color, but by brand,
**so that** I can find my favorite colors and brands quickly.

## Description

<img src=https://user-images.githubusercontent.com/104504965/178994995-0f5534d1-bd7e-447a-9b5c-04d7f7b14237.png width=320px>

## Acceptance criteria

- [ ] Filters are shown at the top
- [ ] Filters work separately
- [ ] Filters work in combination

## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] Filters are drop-downs
- [ ] Setup Storybook
- [ ] Write spec
