### ISSUE TITLE
Favorite page

### ISSUE THREAD

**Issue by sarina-nikolic** [sarina-nikolic/capstone-project#9]
## Value proposition

**As a** user,
**I want to** have a favorite page for my toggled bookmarks,
**so that** I have a quick overview over my favorite items.

## Description

<img src=https://user-images.githubusercontent.com/104504965/178997651-f97c4691-d9c2-447f-be7a-d384373a7f64.png width=320px>

## Acceptance criteria

- [x]  Navigation shows home and favorite page
- [x] shown at the bottom
- [x] not sticky

## Complexity

Medium

## Tasks

- [x] Create branch
- [x] Add navigation/ footer
- [x] set favorite page
- [x] Setup storybook
- [x] Write spec
